spring:
  application:
    name: spring-multi-model-demo

  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        model: tinydolphin:latest

    openai:
      api-key: ${OPEN_AI}
